// benefits-seed.ts
// Developer: Marcus Daley
// Date: 2026-04-21
// Purpose: Seed data for 55+ VA benefits across all 10 categories

import type { BenefitV2 } from '@vetassist/shared-types';

export const BENEFITS_SEED: readonly BenefitV2[] = [

  // ─── Healthcare (8) ───────────────────────────────────────────────────────────

  {
    id: 'hc-001',
    title: 'VA Health Care Enrollment',
    summary: 'Comprehensive medical care at VA facilities nationwide',
    description: 'Veterans who served on active duty and were separated under any condition other than dishonorable may qualify for VA health care. Includes primary care, mental health, specialty care, prescriptions, and preventive services.',
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Served on active duty',
      'Discharge other than dishonorable',
      'Priority groups 1-8 based on service connection and income',
    ],
    applicationSteps: [
      'Complete VA Form 10-10EZ online or at any VA facility',
      'Provide DD-214 discharge paperwork',
      'Receive eligibility determination within 7 days',
    ],
    cfr: '38 CFR Part 17',
    officialUrl: 'https://www.va.gov/health-care/how-to-apply/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['healthcare', 'primary-care', 'mental-health', 'prescriptions'],
  },

  {
    id: 'hc-002',
    title: 'Mental Health Services',
    summary: 'Free mental health care including PTSD, depression, and MST treatment',
    description: 'VA provides free mental health services to veterans including PTSD treatment, depression therapy, military sexual trauma counseling, and substance use programs. No copay for mental health visits.',
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Enrolled in VA health care',
      'Veterans with OTH discharge may qualify for mental health emergency care',
    ],
    applicationSteps: [
      'Enroll in VA health care (10-10EZ)',
      'Request mental health appointment at your VA facility',
      'Same-day mental health appointments available at most VAMCs',
    ],
    cfr: '38 CFR 17.38',
    officialUrl: 'https://www.va.gov/health-care/health-needs-conditions/mental-health/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['mental-health', 'ptsd', 'mst', 'depression', 'no-copay'],
  },

  {
    id: 'hc-003',
    title: 'PACT Act Toxic Exposure Screening',
    summary: 'Free health screenings for veterans exposed to burn pits, Agent Orange, and other toxins',
    description: 'The PACT Act (2022) expanded VA health care to cover veterans exposed to toxic substances including burn pits, Agent Orange, radiation, and contaminated water at Camp Lejeune. Free presumptive conditions coverage — no proof of nexus required for 20+ conditions.',
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Served in Southwest Asia theater after Aug 2, 1990',
      'Vietnam-era veterans for Agent Orange',
      'Camp Lejeune veterans 1953-1987',
      'Post-9/11 veterans for burn pit exposure',
    ],
    applicationSteps: [
      'Contact VA and request PACT Act screening',
      'Complete toxic exposure screening questionnaire',
      'VA enrolls eligible veterans — no prior VA health care enrollment required',
    ],
    cfr: 'Public Law 117-168',
    officialUrl: 'https://www.va.gov/resources/the-pact-act-and-your-va-benefits/',
    stateCode: null,
    isHiddenGem: true,
    tags: ['pact-act', 'burn-pit', 'agent-orange', 'toxic-exposure', 'presumptive'],
  },

  {
    id: 'hc-004',
    title: 'VA Caregiver Support Program',
    summary: 'Monthly stipend, health insurance, and respite care for family caregivers of eligible veterans',
    description: 'The Program of Comprehensive Assistance for Family Caregivers (PCAFC) provides monthly stipends, health care coverage through CHAMPVA, mental health services, respite care, and caregiver training to family members caring for eligible post-9/11 veterans with serious injuries.',
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Veteran served on or after September 11, 2001',
      'Veteran has serious injury (including mental health) incurred or aggravated in the line of duty',
      'Veteran requires personal care services',
      'Caregiver is a family member or surrogate family member',
    ],
    applicationSteps: [
      'Submit VA Form 10-10CG online or at a VA caregiver support program site',
      'VA conducts home visit assessment',
      'Approval decision typically within 45 days',
    ],
    cfr: '38 CFR Part 71',
    officialUrl: 'https://www.caregiver.va.gov/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['caregiver', 'stipend', 'champva', 'respite', 'family'],
  },

  {
    id: 'hc-005',
    title: 'Community Care Network',
    summary: 'VA-authorized care from community (non-VA) providers when VA cannot provide timely access',
    description: "Veterans enrolled in VA health care may receive care from community providers when VA can't provide the service, when wait times exceed VA access standards, or when the veteran lives more than 40 miles from a VA facility. VA pays the community provider directly.",
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Enrolled in VA health care',
      'VA cannot provide the required service',
      'Wait time exceeds VA access standards (20 days for primary/mental health, 28 days for specialty)',
      'Live more than 40 miles from nearest VA facility offering the service',
    ],
    applicationSteps: [
      'Request community care referral from your VA primary care provider',
      'VA authorizes care and sends referral to community provider',
      'Schedule appointment with approved community provider',
    ],
    cfr: '38 CFR Part 17 Subpart F',
    officialUrl: 'https://www.va.gov/COMMUNITYCARE/programs/veterans/VCP/index.asp',
    stateCode: null,
    isHiddenGem: false,
    tags: ['community-care', 'outside-va', 'access', 'non-va'],
  },

  {
    id: 'hc-006',
    title: 'VA Telehealth Services',
    summary: 'Video and phone appointments with VA providers from home',
    description: 'VA Telehealth offers VA Video Connect (video appointments), telephone visits, store-and-forward telehealth (images/data sent to specialists), and remote patient monitoring. Available for primary care, mental health, specialty care, and more.',
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Enrolled in VA health care',
      'Have a device with internet connection for video visits',
    ],
    applicationSteps: [
      'Request telehealth appointment through VA facility or MyHealtheVet',
      'Download the VA Video Connect app',
      'Connect with provider at scheduled time',
    ],
    cfr: '38 CFR Part 17',
    officialUrl: 'https://telehealth.va.gov/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['telehealth', 'video', 'remote', 'home', 'mental-health'],
  },

  {
    id: 'hc-007',
    title: "Women Veterans Health Care",
    summary: 'Specialized health care services exclusively for women veterans',
    description: 'VA provides gender-specific care including gynecology, maternity care, reproductive health, breast and cervical cancer screenings, hormone therapy, and military sexual trauma care. Every VA facility has a designated Women Veterans Program Manager.',
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Female veteran enrolled in VA health care',
      'Some reproductive health services available without enrollment',
    ],
    applicationSteps: [
      'Enroll in VA health care (10-10EZ)',
      'Request Women Veterans Program Manager at your VAMC',
      'Schedule appointment at designated women-specific clinic',
    ],
    cfr: '38 CFR 17.38',
    officialUrl: 'https://www.womenshealth.va.gov/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['women', 'reproductive-health', 'gynecology', 'maternity', 'mst'],
  },

  {
    id: 'hc-008',
    title: 'Burn Pit Registry',
    summary: 'Document toxic exposure for future health claims and research',
    description: 'The Airborne Hazards and Open Burn Pit Registry allows veterans and servicemembers to document their exposure to airborne hazards and burn pits. Registry participation can support future disability claims and contributes to VA research on long-term health effects.',
    category: 'healthcare',
    source: 'official_va',
    eligibilityRules: [
      'Deployed to Southwest Asia theater after August 2, 1990',
      'Served in Afghanistan, Djibouti, Syria, or Uzbekistan after September 11, 2001',
      'Any veteran potentially exposed to open burn pits',
    ],
    applicationSteps: [
      'Register online through the VA Airborne Hazards and Open Burn Pit Registry website',
      'Complete online questionnaire about service locations and health conditions',
      'Optional: Schedule a VA medical evaluation',
    ],
    cfr: 'Public Law 112-260',
    officialUrl: 'https://veteran.mobilehealth.va.gov/AHBurnPitRegistry/',
    stateCode: null,
    isHiddenGem: true,
    tags: ['burn-pit', 'registry', 'airborne-hazards', 'toxic-exposure', 'documentation'],
  },

  // ─── Education (7) ────────────────────────────────────────────────────────────

  {
    id: 'ed-001',
    title: 'Post-9/11 GI Bill (Chapter 33)',
    summary: 'Up to 100% tuition coverage, housing allowance, and book stipend',
    description: 'The Post-9/11 GI Bill provides up to 36 months of education benefits for college, vocational/technical training, on-the-job training, flight training, correspondence training, licensing and national testing programs, entrepreneurship training, and tutorial assistance.',
    category: 'education',
    source: 'official_va',
    eligibilityRules: [
      'Served at least 90 days on active duty after September 10, 2001',
      'Received an honorable discharge',
      'Benefits percentage based on length of qualifying service (40%-100%)',
    ],
    applicationSteps: [
      'Apply online at VA.gov using VA Form 22-1990',
      'Receive Certificate of Eligibility',
      'Certify enrollment with your school each semester',
    ],
    cfr: '38 CFR Part 21 Subpart K',
    officialUrl: 'https://www.va.gov/education/about-gi-bill-benefits/post-9-11/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['gi-bill', 'tuition', 'housing-allowance', 'books', 'college'],
  },

  {
    id: 'ed-002',
    title: 'Montgomery GI Bill Active Duty (Chapter 30)',
    summary: 'Monthly education benefit for active duty veterans who contributed to MGIB',
    description: 'Provides monthly payments for education and training. Must have contributed $1,200 to the program during active duty service. Up to 36 months of benefits available for college, business, technical, and vocational programs.',
    category: 'education',
    source: 'official_va',
    eligibilityRules: [
      'Honorable discharge',
      'High school diploma or GED before applying for benefits',
      'Contributed $1,200 to the program during service',
      'Meet minimum active duty service requirements',
    ],
    applicationSteps: [
      'Apply online at VA.gov using VA Form 22-1990',
      'Verify enrollment monthly via Web Automated Verification of Enrollment (WAVE)',
    ],
    cfr: '38 CFR Part 21 Subpart A',
    officialUrl: 'https://www.va.gov/education/about-gi-bill-benefits/montgomery-active-duty/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['gi-bill', 'mgib', 'monthly-payment', 'college', 'chapter-30'],
  },

  {
    id: 'ed-003',
    title: 'Vocational Rehabilitation & Employment (Chapter 31)',
    summary: 'Career services, job training, and education for veterans with service-connected disabilities',
    description: "VR&E (also known as Voc Rehab) helps veterans with service-connected disabilities prepare for, find, and keep suitable jobs. Services include job training, resume assistance, interview coaching, job search help, and education assistance. Veterans with serious disabilities may receive independent living services.",
    category: 'education',
    source: 'official_va',
    eligibilityRules: [
      'Have a service-connected disability rating of at least 10%',
      'Receive a discharge other than dishonorable',
      'Have an employment handicap',
    ],
    applicationSteps: [
      'Apply online at VA.gov using VA Form 28-1900',
      'Attend initial evaluation with a Vocational Rehabilitation Counselor',
      'Develop an Individualized Plan for Employment (IPE)',
    ],
    cfr: '38 CFR Part 21 Subpart A',
    officialUrl: 'https://www.va.gov/careers-employment/vocational-rehabilitation/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['voc-rehab', 'job-training', 'employment', 'disability', 'chapter-31'],
  },

  {
    id: 'ed-004',
    title: "Survivors' and Dependents' Educational Assistance (Chapter 35)",
    summary: 'Education benefits for dependents of veterans with permanent and total disabilities',
    description: 'Provides education and training opportunities to eligible dependents and survivors of certain veterans. Eligible children may receive benefits between ages 18-26. Spouses may receive benefits for up to 10 years.',
    category: 'education',
    source: 'official_va',
    eligibilityRules: [
      'Veteran has permanent and total service-connected disability',
      'Veteran died from service-connected disability',
      'Veteran is missing in action or a prisoner of war',
      'Dependent must meet age requirements',
    ],
    applicationSteps: [
      'Apply online at VA.gov using VA Form 22-5490',
      'Provide documentation of veteran relationship',
      'Enroll in qualifying education or training program',
    ],
    cfr: '38 CFR Part 21 Subpart C',
    officialUrl: 'https://www.va.gov/education/survivor-dependent-benefits/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['survivor', 'dependent', 'education', 'chapter-35', 'family'],
  },

  {
    id: 'ed-005',
    title: 'STEM Scholarship (Rogers STEM Scholarship)',
    summary: 'Additional 9 months of Post-9/11 GI Bill benefits for STEM degree students',
    description: 'The Edith Nourse Rogers STEM Scholarship provides up to 9 additional months of GI Bill benefits (worth up to $30,000) for veterans and fry scholars pursuing high-demand STEM (Science, Technology, Engineering, Math) and health care fields.',
    category: 'education',
    source: 'official_va',
    eligibilityRules: [
      'Eligible for Post-9/11 GI Bill benefits',
      'Pursuing undergraduate degree in STEM field, or enrolled in health care professional education',
      'Have used or be entitled to use all Post-9/11 GI Bill benefits',
      'Must have 6 months or fewer of remaining benefits',
    ],
    applicationSteps: [
      'Apply online at VA.gov using VA Form 22-10203',
      'Provide confirmation of STEM program enrollment',
      'School certifies enrollment to VA',
    ],
    cfr: 'Public Law 115-48',
    officialUrl: 'https://www.va.gov/education/other-va-education-benefits/stem-scholarship/',
    stateCode: null,
    isHiddenGem: true,
    tags: ['stem', 'scholarship', 'gi-bill', 'extension', 'technology'],
  },

  {
    id: 'ed-006',
    title: 'Yellow Ribbon Program',
    summary: 'VA and school share costs above the public in-state tuition cap for private or out-of-state schools',
    description: 'Participating schools voluntarily enter an agreement with VA to fund tuition and fees exceeding the national maximum cap. VA matches the school contribution, covering the gap for veterans at private schools or out-of-state public schools.',
    category: 'education',
    source: 'official_va',
    eligibilityRules: [
      'Eligible for Post-9/11 GI Bill at 100% level',
      'Not on active duty',
      'Attending a participating school',
    ],
    applicationSteps: [
      'Verify your school participates in Yellow Ribbon on VA.gov',
      'Contact school financial aid office for Yellow Ribbon application',
      'Submit GI Bill enrollment certification',
    ],
    cfr: '38 USC 3317',
    officialUrl: 'https://www.va.gov/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['yellow-ribbon', 'private-school', 'tuition', 'gi-bill', 'out-of-state'],
  },

  {
    id: 'ed-007',
    title: 'On-the-Job Training & Apprenticeships',
    summary: 'Use GI Bill benefits while earning a paycheck in an apprenticeship or OJT program',
    description: 'Veterans can use GI Bill benefits while training in an on-the-job training (OJT) or apprenticeship program. VA pays a monthly housing allowance while the employer pays wages, allowing veterans to earn income and benefits simultaneously.',
    category: 'education',
    source: 'official_va',
    eligibilityRules: [
      'Eligible for Post-9/11, MGIB, or MGIB-SR GI Bill',
      'Employer must have VA-approved OJT or apprenticeship program',
    ],
    applicationSteps: [
      'Find VA-approved OJT/apprenticeship programs at VA.gov or through your State Approving Agency',
      'Apply for GI Bill benefits using VA Form 22-1990',
      'Employer submits monthly certification of training hours',
    ],
    cfr: '38 CFR 21.4262',
    officialUrl: 'https://www.va.gov/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['apprenticeship', 'ojt', 'on-the-job', 'gi-bill', 'trade'],
  },

  // ─── Housing (6) ──────────────────────────────────────────────────────────────

  {
    id: 'ho-001',
    title: 'VA Home Loan Guarantee',
    summary: 'Buy a home with no down payment and no private mortgage insurance',
    description: "VA-backed home loans allow eligible veterans to purchase a home with no down payment, no private mortgage insurance (PMI), competitive interest rates, and limited closing costs. VA guarantees a portion of the loan, allowing lenders to offer better terms. Available for purchase, refinance (IRRRL), and cash-out refinance.",
    category: 'housing',
    source: 'official_va',
    eligibilityRules: [
      'Minimum active duty service (90 days wartime, 181 days peacetime, or 6 years Guard/Reserve)',
      'Honorable or general discharge',
      'Obtain Certificate of Eligibility (COE)',
      'Meet lender credit and income requirements',
    ],
    applicationSteps: [
      'Obtain Certificate of Eligibility via VA.gov or through lender',
      'Find a VA-approved lender',
      'Get pre-approved and find home',
      'Request VA appraisal during purchase process',
    ],
    cfr: '38 CFR Part 36',
    officialUrl: 'https://www.va.gov/housing-assistance/home-loans/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['home-loan', 'no-down-payment', 'mortgage', 'purchase', 'refinance'],
  },

  {
    id: 'ho-002',
    title: 'Specially Adapted Housing (SAH) Grant',
    summary: 'Up to $109,986 grant to build or modify a home for veterans with severe service-connected disabilities',
    description: 'The Specially Adapted Housing grant helps veterans with certain severe service-connected disabilities buy or build an adapted home or modify an existing home. The grant can be used up to 3 times for a lifetime benefit total.',
    category: 'housing',
    source: 'official_va',
    eligibilityRules: [
      'Own or plan to own the home',
      'Have one of these service-connected disabilities: loss or loss of use of both lower extremities, blindness in both eyes, loss or loss of use of one lower extremity together with residuals of organic disease or injury, loss or loss of use of one lower extremity and one upper extremity',
    ],
    applicationSteps: [
      'Apply using VA Form 26-4555',
      'VA determines eligibility and grant amount',
      'Work with VA representative to plan modifications',
    ],
    cfr: '38 CFR Part 36 Subpart C',
    officialUrl: 'https://www.va.gov/housing-assistance/adaptive-housing-grants/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['adaptive-housing', 'sah', 'grant', 'disability', 'modification'],
  },

  {
    id: 'ho-003',
    title: 'Special Housing Adaptation (SHA) Grant',
    summary: 'Up to $22,036 grant for home modifications for veterans with specific service-connected disabilities',
    description: 'The Special Housing Adaptation grant assists veterans who have specific service-connected disabilities with acquiring or modifying a home. Designed for veterans with burns, blindness, or loss of use of both hands.',
    category: 'housing',
    source: 'official_va',
    eligibilityRules: [
      'Have specific service-connected disabilities including severe burns, blindness in both eyes, or loss or loss of use of both hands',
      'Own or plan to own the home or a family member must own the home',
    ],
    applicationSteps: [
      'Apply using VA Form 26-4555',
      'VA evaluates eligibility and maximum grant amount',
      'Coordinate with VA Adaptive Housing Specialist',
    ],
    cfr: '38 CFR Part 36 Subpart C',
    officialUrl: 'https://www.va.gov/housing-assistance/adaptive-housing-grants/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['sha', 'adaptive-housing', 'grant', 'burns', 'blindness'],
  },

  {
    id: 'ho-004',
    title: 'Home Improvements and Structural Alterations (HISA) Grant',
    summary: 'Up to $6,800 for home modifications related to service-connected disability — widely unknown',
    description: 'The HISA grant provides funding for medically necessary improvements and structural alterations to veterans\' primary residence. Available for both service-connected and non-service-connected disabilities. Service-connected veterans may receive up to $6,800; non-service-connected up to $2,000.',
    category: 'housing',
    source: 'official_va',
    eligibilityRules: [
      'Enrolled in VA health care',
      'Modification is medically necessary as prescribed by VA physician',
      'Modification is to primary residence',
    ],
    applicationSteps: [
      'Get prescription for modification from VA treating physician',
      'Apply through local VA Medical Center prosthetics department',
      'Obtain contractor bids and submit with application',
    ],
    cfr: '38 CFR 17.3101',
    officialUrl: 'https://www.va.gov/housing-assistance/home-loans/program-types/',
    stateCode: null,
    isHiddenGem: true,
    tags: ['hisa', 'home-modification', 'grant', 'accessibility', 'medically-necessary'],
  },

  {
    id: 'ho-005',
    title: 'HUD-VASH Vouchers',
    summary: 'Housing vouchers plus VA case management services for homeless veterans',
    description: 'The HUD-VA Supportive Housing (HUD-VASH) program combines HUD Housing Choice Voucher rental assistance with VA supportive services to help veterans experiencing homelessness find and sustain permanent housing.',
    category: 'housing',
    source: 'official_va',
    eligibilityRules: [
      'Veteran experiencing homelessness or at risk of homelessness',
      'Eligible for VA health care services',
      'Meet HUD income requirements',
    ],
    applicationSteps: [
      'Contact local VA Medical Center homeless program coordinator',
      'Complete VA eligibility assessment',
      'Work with HUD-VASH case manager to find housing',
    ],
    cfr: '24 CFR Part 983',
    officialUrl: 'https://www.va.gov/homeless/hud-vash.asp',
    stateCode: null,
    isHiddenGem: false,
    tags: ['homeless', 'housing-voucher', 'hud-vash', 'rental-assistance', 'case-management'],
  },

  {
    id: 'ho-006',
    title: 'VA Native American Direct Loan (NADL)',
    summary: 'Direct VA home loans for Native American veterans on federal trust land',
    description: 'The NADL program provides direct loans from VA (not just a guarantee) to Native American veterans to purchase, construct, or improve homes on federal trust land. Also available for refinancing.',
    category: 'housing',
    source: 'official_va',
    eligibilityRules: [
      'Native American veteran or veteran married to a Native American',
      'Tribal government must have a Memorandum of Understanding with VA',
      'Meet credit and income requirements',
    ],
    applicationSteps: [
      'Confirm tribal participation in NADL program',
      'Obtain Certificate of Eligibility',
      'Apply directly through VA NADL program',
    ],
    cfr: '38 CFR Part 36 Subpart D',
    officialUrl: 'https://www.va.gov/housing-assistance/home-loans/loan-types/native-american-direct-loan/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['native-american', 'nadl', 'direct-loan', 'trust-land', 'tribal'],
  },

  // ─── Employment (5) ───────────────────────────────────────────────────────────

  {
    id: 'em-001',
    title: 'Transition Assistance Program (TAP)',
    summary: 'Job search, resume writing, and career counseling before separation from service',
    description: "TAP provides separating servicemembers with career readiness services including job search assistance, resume preparation, interview skills, and connections to employment resources. Participation is mandatory for most servicemembers separating after 180+ days of active duty.",
    category: 'employment',
    source: 'official_va',
    eligibilityRules: [
      'Separating or retiring servicemember',
      'Mandatory for those separating after 180+ days of active duty',
    ],
    applicationSteps: [
      'Work with your command to schedule TAP classes',
      'Attend pre-separation counseling',
      'Complete Individual Transition Plan (ITP)',
    ],
    cfr: '10 USC 1142',
    officialUrl: 'https://www.tapevents.org/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['transition', 'resume', 'job-search', 'career', 'separation'],
  },

  {
    id: 'em-002',
    title: 'SkillBridge Program',
    summary: 'Up to 6 months with a civilian employer while still on active duty with full military pay',
    description: 'DoD SkillBridge allows servicemembers to gain civilian work experience during the last 180 days of military service. Participants work for approved civilian employers while still receiving their full military pay and benefits — a career head-start with zero financial risk.',
    category: 'employment',
    source: 'official_va',
    eligibilityRules: [
      'Active duty servicemember within 180 days of separation',
      'Command approval required',
      'Employer must be DoD-approved SkillBridge partner',
    ],
    applicationSteps: [
      'Search approved employers at skillbridge.defense.gov',
      'Apply to employers and obtain command approval',
      'Begin internship/apprenticeship while receiving full military pay',
    ],
    cfr: '10 USC 1143',
    officialUrl: 'https://skillbridge.osd.mil/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['skillbridge', 'internship', 'active-duty', 'transition', 'civilian'],
  },

  {
    id: 'em-003',
    title: 'Veterans Employment Through Technology Education Courses (VET TEC)',
    summary: 'High-tech training with top tech companies — tuition covered, housing stipend paid',
    description: 'VET TEC is a pilot program that covers the full cost of approved high-technology training programs from industry-leading providers. VA pays tuition and fees directly to the provider, plus a monthly housing allowance during training. Designed for veterans interested in technology careers.',
    category: 'employment',
    source: 'official_va',
    eligibilityRules: [
      'Eligible for VA education benefits',
      'At least 1 day of remaining GI Bill entitlement',
    ],
    applicationSteps: [
      'Apply online at VA.gov using VA Form 22-0994',
      'Select from approved training providers',
      'Provider reports progress to VA',
    ],
    cfr: 'Public Law 115-48',
    officialUrl: 'https://www.va.gov/education/other-va-education-benefits/vet-tec-program/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['vet-tec', 'technology', 'coding', 'training', 'stipend'],
  },

  {
    id: 'em-004',
    title: 'Veterans Preference in Federal Hiring',
    summary: 'Point preferences in federal civil service hiring for veterans',
    description: "Veterans' preference gives eligible veterans a competitive advantage in hiring for most federal government positions. 5-point preference for honorable veterans; 10-point preference for veterans with service-connected disabilities. Certain veterans with 30%+ ratings are non-competitively placed in some positions.",
    category: 'employment',
    source: 'official_va',
    eligibilityRules: [
      '5-point: Honorable or general discharge, served during defined periods',
      '10-point: Service-connected disability or received Purple Heart',
      'Campaign Badge or Expeditionary Medal also qualify for 5-point',
    ],
    applicationSteps: [
      'Claim preference on USAJOBS profile',
      'Submit SF-15 (Application for 10-point Veterans Preference) when required',
      'Attach DD-214 and disability rating documentation',
    ],
    cfr: '5 CFR Part 211',
    officialUrl: 'https://www.fedshirevets.gov/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['federal-hiring', 'veterans-preference', 'civil-service', 'usajobs', 'priority'],
  },

  {
    id: 'em-005',
    title: 'Small Business Administration Veteran Loans (SBA)',
    summary: 'Business loans and venture capital access for veteran-owned businesses',
    description: "SBA offers veteran-specific loan programs including the Military Reservist Economic Injury Disaster Loan (MREIDL), fee waivers on SBA 7(a) loans under $150,000 for veteran-owned businesses, and access to the Boots to Business entrepreneurship training program.",
    category: 'employment',
    source: 'vso_verified',
    eligibilityRules: [
      'Business is at least 51% veteran-owned',
      'Veteran must be involved in daily management',
      'Meet SBA small business size standards',
    ],
    applicationSteps: [
      'Register business as veteran-owned in SAM.gov',
      'Contact local SBA district office or SCORE mentor',
      'Apply for appropriate SBA loan program',
    ],
    cfr: '13 CFR Part 125',
    officialUrl: 'https://www.sba.gov/business-guide/grow-your-business/veteran-owned-businesses',
    stateCode: null,
    isHiddenGem: false,
    tags: ['small-business', 'entrepreneur', 'sba', 'loan', 'veteran-owned'],
  },

  // ─── Compensation (7) ─────────────────────────────────────────────────────────

  {
    id: 'co-001',
    title: 'VA Disability Compensation',
    summary: 'Monthly tax-free payment for service-connected physical or mental health conditions',
    description: 'VA disability compensation provides a monthly tax-free payment to veterans who have physical or mental health conditions related to their military service. Ratings from 0% to 100% in 10% increments determine the payment amount. Combined ratings follow the VA "whole person" formula.',
    category: 'compensation',
    source: 'official_va',
    eligibilityRules: [
      'Served on active duty, active duty for training, or inactive duty training',
      'Discharge other than dishonorable',
      'Current diagnosis for physical or mental condition',
      'In-service event, injury, or illness (or aggravation of pre-existing condition)',
      'Nexus (connection) between current condition and military service',
    ],
    applicationSteps: [
      'File VA Form 21-526EZ online, by mail, or at a VA regional office',
      'Submit supporting evidence (service records, medical records, buddy statements)',
      'Attend C&P (Compensation and Pension) exam if requested',
      'Receive rating decision — appeal if necessary',
    ],
    cfr: '38 CFR Part 4',
    officialUrl: 'https://www.va.gov/disability/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['disability', 'compensation', 'rating', 'monthly-payment', 'tax-free'],
  },

  {
    id: 'co-002',
    title: 'Total Disability Individual Unemployability (TDIU)',
    summary: 'Receive 100% compensation rate when combined rating is below 100% but you cannot work',
    description: "TDIU allows veterans who cannot maintain substantially gainful employment due to service-connected disabilities to receive compensation at the 100% rate even if their combined rating is below 100%. Requires a rating of at least 60% for one disability or 70%+ combined (with one disability at 40%+).",
    category: 'compensation',
    source: 'official_va',
    eligibilityRules: [
      'Service-connected disability(ies) prevent substantially gainful employment',
      'Single rating of at least 60%, OR combined rating of at least 70% with one disability at 40%+',
    ],
    applicationSteps: [
      'Submit VA Form 21-8940 (Veteran\'s Application for Increased Compensation Based on Unemployability)',
      'Provide employment history and medical evidence',
      'VA may request additional C&P exam',
    ],
    cfr: '38 CFR 4.16',
    officialUrl: 'https://www.va.gov/disability/eligibility/special-claims/unemployability/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['tdiu', 'unemployability', '100-percent', 'unable-to-work', 'disability'],
  },

  {
    id: 'co-003',
    title: 'Dependency and Indemnity Compensation (DIC)',
    summary: 'Tax-free monthly benefit for surviving spouses and dependents of veterans who died from service-connected causes',
    description: 'DIC provides a monthly tax-free benefit to eligible survivors of veterans who died from a service-connected condition or while receiving (or entitled to receive) VA compensation for total disability. Surviving spouses, children, and parents may qualify.',
    category: 'compensation',
    source: 'official_va',
    eligibilityRules: [
      'Veteran died from service-connected disability',
      'Veteran died from any cause while receiving VA compensation for a totally disabling condition for at least 10 years',
      'Survivor must meet relationship and dependency requirements',
    ],
    applicationSteps: [
      'Apply using VA Form 21P-534EZ',
      'Submit veteran\'s death certificate',
      'Provide marriage certificate or proof of dependency',
    ],
    cfr: '38 CFR Part 3 Subpart B',
    officialUrl: 'https://www.va.gov/disability/dependency-indemnity-compensation/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['dic', 'survivor', 'spouse', 'death', 'service-connected'],
  },

  {
    id: 'co-004',
    title: 'Special Monthly Compensation (SMC)',
    summary: 'Additional compensation above standard rates for veterans with severe disabilities',
    description: 'SMC provides additional monthly tax-free compensation for veterans with specific severe service-connected disabilities such as loss of limb(s), blindness, need for regular aid and attendance of another person, or being housebound. SMC rates are higher than standard disability compensation rates.',
    category: 'compensation',
    source: 'official_va',
    eligibilityRules: [
      'Must have one of the qualifying severe disabilities: loss or loss of use of limbs, blindness, deafness, need for aid and attendance, or housebound status',
      'Disability must be service-connected',
    ],
    applicationSteps: [
      'SMC is often automatically considered when VA rates a claim',
      'You may also specifically request SMC review',
      'Submit VA Form 21-2680 for Aid & Attendance evaluation',
    ],
    cfr: '38 USC 1114',
    officialUrl: 'https://www.va.gov/disability/eligibility/special-claims/special-monthly-compensation/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['smc', 'special-monthly', 'severe-disability', 'loss-of-limb', 'aid-attendance'],
  },

  {
    id: 'co-005',
    title: 'Clothing Allowance',
    summary: 'Annual payment to replace clothing damaged by prosthetics or skin medications',
    description: 'Veterans with service-connected disabilities who use prosthetic or orthopedic devices, or who use prescribed medications that damage clothing, may receive an annual clothing allowance payment. Many veterans with eligible conditions simply do not know to claim this benefit.',
    category: 'compensation',
    source: 'official_va',
    eligibilityRules: [
      'Service-connected disability requires use of a prosthetic or orthopedic appliance that tends to wear out or tear clothing',
      'OR service-connected skin condition requires prescribed topical medication that damages clothing',
    ],
    applicationSteps: [
      'Apply using VA Form 10-8678 before August 1 each year',
      'Submit through your local VA Medical Center Prosthetics department',
      'Physician must confirm the qualifying condition',
    ],
    cfr: '38 CFR 3.810',
    officialUrl: 'https://www.va.gov/disability/eligibility/special-claims/clothing-allowance/',
    stateCode: null,
    isHiddenGem: true,
    tags: ['clothing-allowance', 'prosthetic', 'annual-payment', 'skin-condition', 'overlooked'],
  },

  {
    id: 'co-006',
    title: 'Aid and Attendance (A&A)',
    summary: 'Additional monthly benefit for veterans who need help with daily living activities',
    description: 'Aid and Attendance is a higher level of pension for veterans who require help with daily activities such as bathing, dressing, feeding, or who are bedridden or in a nursing home. Veterans receiving VA Pension with a high disability rating may qualify for this additional amount.',
    category: 'compensation',
    source: 'official_va',
    eligibilityRules: [
      'Receiving VA Pension',
      'Need help with daily living activities (bathing, dressing, eating)',
      'OR blind or nearly blind',
      'OR residing in a nursing home due to mental or physical incapacity',
    ],
    applicationSteps: [
      'Apply for VA Pension first if not already receiving it',
      'Request Aid & Attendance consideration by letter or submitting VA Form 21-2680',
      'VA medical examiner completes examination form',
    ],
    cfr: '38 CFR 3.352',
    officialUrl: 'https://www.va.gov/pension/aid-attendance-housebound/',
    stateCode: null,
    isHiddenGem: true,
    tags: ['aid-attendance', 'pension', 'daily-living', 'nursing-home', 'caregiver'],
  },

  {
    id: 'co-007',
    title: 'Combat-Related Special Compensation (CRSC)',
    summary: 'Tax-free payment restoring military retirement pay offset by disability compensation',
    description: 'CRSC provides a monthly tax-free compensation to military retirees with combat-related disabilities. Unlike standard disability compensation that offsets military retirement pay, CRSC allows retirees to receive both military retirement and disability-related compensation without a dollar-for-dollar offset.',
    category: 'compensation',
    source: 'official_va',
    eligibilityRules: [
      'Military retiree (20+ years of service or medical retirement)',
      'Have combat-related disability (incurred in combat, training for combat, or due to instrumentality of war)',
      'Disability is service-connected by VA',
    ],
    applicationSteps: [
      'Apply through your military branch (not VA)',
      'Submit CRSC application with VA rating decision',
      'Branch determines CRSC eligibility and amount',
    ],
    cfr: '10 USC 1413a',
    officialUrl: 'https://militarypay.defense.gov/Benefits/CRSC/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['crsc', 'military-retirement', 'combat-related', 'tax-free', 'offset'],
  },

  // ─── Pension (3) ──────────────────────────────────────────────────────────────

  {
    id: 'pe-001',
    title: "Veterans Pension",
    summary: 'Monthly income supplement for wartime veterans with limited income and assets',
    description: "VA Pension is a benefit for wartime veterans who meet certain service requirements and are permanently and totally disabled, or are at least 65 years old, and have income and assets below limits set by Congress. Not related to service-connected disability — based on financial need.",
    category: 'pension',
    source: 'official_va',
    eligibilityRules: [
      'Served on active duty at least 90 days, at least 1 day during a wartime period',
      'Discharged under conditions other than dishonorable',
      'At least 65 years old OR permanently and totally disabled',
      'Meet income and net worth limits',
    ],
    applicationSteps: [
      'Apply using VA Form 21P-527EZ',
      'Provide income and asset information',
      'VA calculates pension based on income limit minus actual income',
    ],
    cfr: '38 CFR Part 3 Subpart A',
    officialUrl: 'https://www.va.gov/pension/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['pension', 'wartime', 'income', 'elderly', 'financial-need'],
  },

  {
    id: 'pe-002',
    title: "Survivors Pension",
    summary: 'Monthly income-based benefit for surviving spouses and children of wartime veterans',
    description: "VA Survivors Pension (formerly called Death Pension) provides a monthly benefit to low-income surviving spouses and unmarried children of deceased wartime veterans. The benefit is need-based — VA pays the difference between household income and the maximum annual pension rate.",
    category: 'pension',
    source: 'official_va',
    eligibilityRules: [
      'Surviving spouse not remarried after December 31, 1970, or',
      'Unmarried child of deceased wartime veteran',
      'Veteran must have served during a wartime period',
      'Household income must be below yearly limit',
    ],
    applicationSteps: [
      'Apply using VA Form 21P-534EZ',
      'Provide veteran\'s service and death records',
      'Provide annual income and net worth information',
    ],
    cfr: '38 CFR Part 3 Subpart B',
    officialUrl: 'https://www.va.gov/pension/survivors-pension/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['survivors-pension', 'spouse', 'dependent', 'death', 'income-based'],
  },

  {
    id: 'pe-003',
    title: 'Housebound Benefits',
    summary: 'Additional pension amount for veterans substantially confined to home due to disability',
    description: 'The Housebound benefit provides a higher monthly pension amount to veterans who are permanently disabled and substantially confined to their immediate premises due to their disability. Recipients must already be eligible for VA Pension.',
    category: 'pension',
    source: 'official_va',
    eligibilityRules: [
      'Receiving VA Pension',
      'Permanent disability rated at 100% by VA',
      'Another disability rated at 60%+, or',
      'Substantially confined to home due to disability',
    ],
    applicationSteps: [
      'Already receiving VA Pension',
      'Submit medical evidence of confinement to your VA regional office',
      'VA evaluates and adjusts pension to housebound rate if eligible',
    ],
    cfr: '38 CFR 3.351',
    officialUrl: 'https://www.va.gov/pension/aid-attendance-housebound/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['housebound', 'pension', 'confined', 'disability', 'home-bound'],
  },

  // ─── Insurance (5) ────────────────────────────────────────────────────────────

  {
    id: 'in-001',
    title: "Servicemembers' Group Life Insurance (SGLI)",
    summary: 'Low-cost group life insurance for active duty servicemembers — up to $500,000 coverage',
    description: "SGLI provides automatic life insurance coverage to eligible active duty servicemembers, reservists, and National Guard members. Coverage of up to $500,000 is automatic unless declined. Also covers spouse (FSGLI) and dependent children.",
    category: 'insurance',
    source: 'official_va',
    eligibilityRules: [
      'Active duty servicemember, officer, or enlisted',
      'National Guard or Reserve member under orders',
      'Coverage is automatic — must actively decline or reduce',
    ],
    applicationSteps: [
      'Automatic enrollment at accession — review coverage level',
      'Update beneficiaries via SGLI Online Enrollment System (SOES)',
      'Review FSGLI coverage for spouse',
    ],
    cfr: '38 CFR Part 9',
    officialUrl: 'https://www.va.gov/life-insurance/options-eligibility/sgli/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['sgli', 'life-insurance', 'active-duty', 'family', 'coverage'],
  },

  {
    id: 'in-002',
    title: "Veterans' Group Life Insurance (VGLI)",
    summary: 'Continue SGLI life insurance coverage after separation — convert within 1 year 120 days',
    description: "VGLI allows veterans to convert their SGLI coverage to renewable term insurance after separating from service. If applied within 240 days of separation, no medical underwriting required. Coverage amount equals SGLI coverage at separation. Renewable every 5 years.",
    category: 'insurance',
    source: 'official_va',
    eligibilityRules: [
      'Had SGLI coverage at separation',
      'Apply within 1 year and 120 days of separation for automatic coverage',
      'Apply within 240 days for no medical underwriting',
    ],
    applicationSteps: [
      'Apply online at OPM.gov or mail VA Form SGLV 8714',
      'No physical required if applying within 240 days',
      'Pay premiums directly to Office of Servicemembers\' Group Life Insurance',
    ],
    cfr: '38 CFR Part 9',
    officialUrl: 'https://www.va.gov/life-insurance/options-eligibility/vgli/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['vgli', 'life-insurance', 'post-separation', 'term', 'conversion'],
  },

  {
    id: 'in-003',
    title: 'VALife Insurance',
    summary: 'Whole life insurance for veterans with service-connected disabilities — guaranteed acceptance',
    description: "VALife is a whole life insurance program for veterans with any level of service-connected disability. Guaranteed acceptance — no medical questions asked. Coverage from $10,000 to $40,000 in $10,000 increments. Builds cash value over time.",
    category: 'insurance',
    source: 'official_va',
    eligibilityRules: [
      'Veterans with service-connected disability (any rating)',
      'Age 80 or younger at application',
    ],
    applicationSteps: [
      'Apply online at va.gov/life-insurance or call 800-419-1473',
      'No medical exam required',
      'Coverage effective 2 years after enrollment for non-service-connected conditions',
    ],
    cfr: '38 USC 1977',
    officialUrl: 'https://www.va.gov/life-insurance/options-eligibility/valife/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['valife', 'whole-life', 'service-connected', 'guaranteed', 'cash-value'],
  },

  {
    id: 'in-004',
    title: 'VA Dental Insurance Program (VADIP)',
    summary: 'Discounted dental insurance for veterans and family members not otherwise eligible for VA dental care',
    description: "VADIP offers affordable dental insurance through Delta Dental and MetLife to veterans enrolled in VA health care and their families. Monthly premiums starting around $12/month for basic coverage. Note: Some veterans are eligible for free VA dental care — check eligibility before enrolling in VADIP.",
    category: 'insurance',
    source: 'official_va',
    eligibilityRules: [
      'Enrolled in VA health care',
      'Not already eligible for comprehensive VA dental care (which would be free)',
    ],
    applicationSteps: [
      'Review VA dental care eligibility first',
      'Enroll in VADIP at Delta Dental or MetLife websites',
      'Pay monthly premiums directly to insurance carrier',
    ],
    cfr: '38 USC 1712A',
    officialUrl: 'https://www.va.gov/dental-care/dental-insurance/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['dental', 'insurance', 'vadip', 'discount', 'family'],
  },

  {
    id: 'in-005',
    title: 'Traumatic Injury Protection (TSGLI)',
    summary: 'Lump-sum payment for severe traumatic injuries suffered during service',
    description: "TSGLI provides short-term financial assistance to servicemembers who suffer severe losses from traumatic injuries — including limb loss, sight loss, hearing loss, burns, and coma. Lump-sum payments range from $25,000 to $100,000. Retroactive eligibility available for October 7, 2001 forward.",
    category: 'insurance',
    source: 'official_va',
    eligibilityRules: [
      'Had SGLI coverage at time of traumatic event',
      'Suffered qualifying traumatic injury during service',
      'Loss must meet the defined threshold for the specific type of injury',
    ],
    applicationSteps: [
      'Apply through your military branch TSGLI office',
      'Submit VA Form SGLV 8600 with medical documentation',
      'Branch reviews and makes payment determination',
    ],
    cfr: '38 CFR Part 9',
    officialUrl: 'https://www.va.gov/life-insurance/options-eligibility/tsgli/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['tsgli', 'traumatic-injury', 'lump-sum', 'limb-loss', 'sgli'],
  },

  // ─── Burial (4) ───────────────────────────────────────────────────────────────

  {
    id: 'bu-001',
    title: 'National Cemetery Burial',
    summary: 'Free burial at a national cemetery including plot, opening, and marker',
    description: "Veterans with an honorable or general discharge are eligible for burial in a VA national cemetery at no cost. Benefits include the burial plot, opening and closing of the grave, liner, grave marker, and perpetual care. Spouses and dependent children may also be eligible for burial.",
    category: 'burial',
    source: 'official_va',
    eligibilityRules: [
      'Honorable or general discharge from active duty',
      'Died during active service',
      'Spouses and dependent children of eligible veterans',
    ],
    applicationSteps: [
      'At time of need, contact the National Cemetery Scheduling Office at 800-535-1117',
      'Provide DD-214 or other service documentation',
      'Funeral home typically coordinates with the national cemetery',
    ],
    cfr: '38 CFR Part 38',
    officialUrl: 'https://www.va.gov/burials-memorials/eligibility/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['burial', 'national-cemetery', 'free', 'grave-marker', 'perpetual-care'],
  },

  {
    id: 'bu-002',
    title: 'Burial Allowance',
    summary: 'Reimbursement up to $2,000 for burial and funeral expenses',
    description: "VA may pay a burial allowance of up to $2,000 for service-connected death, or up to $948 for non-service-connected death (with hospitalization at VA expense). Additional plot/interment allowance of up to $948 for veterans not buried in a national cemetery. Amounts adjust annually.",
    category: 'burial',
    source: 'official_va',
    eligibilityRules: [
      'Veteran was discharged under conditions other than dishonorable',
      'VA was paying compensation or pension at time of death, or veteran died in VA facility',
      'Service-connected death or financial hardship',
    ],
    applicationSteps: [
      'Apply using VA Form 21P-530 within 2 years of burial',
      'Provide funeral home receipts',
      'Submit death certificate and DD-214',
    ],
    cfr: '38 CFR Part 3 Subpart F',
    officialUrl: 'https://www.va.gov/burials-memorials/veterans-burial-allowance/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['burial-allowance', 'funeral', 'reimbursement', 'death', 'financial'],
  },

  {
    id: 'bu-003',
    title: 'Presidential Memorial Certificate',
    summary: 'Signed certificate from the President honoring the memory of honorably discharged veterans',
    description: "The Presidential Memorial Certificate (PMC) is an engraved paper certificate signed by the President, expressing the nation's gratitude for a veteran's service. Available to next of kin and loved ones of honorably discharged deceased veterans at no charge.",
    category: 'burial',
    source: 'official_va',
    eligibilityRules: [
      'Deceased veteran with honorable discharge',
      'Requested by next of kin, other loved ones, or representative',
    ],
    applicationSteps: [
      'Apply online at VA.gov or by mail using VA Form 40-0247',
      'Provide DD-214 or proof of honorable service',
      'Allow 4-6 weeks for delivery',
    ],
    cfr: '38 USC 112',
    officialUrl: 'https://www.va.gov/burials-memorials/memorial-items/presidential-memorial-certificates/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['presidential-certificate', 'memorial', 'honor', 'deceased', 'family'],
  },

  {
    id: 'bu-004',
    title: 'Memorial Items (Headstones, Markers, Medallions)',
    summary: 'Free grave markers, headstones, and Bronze Flag Cases for eligible veterans',
    description: "VA provides free headstones and markers for the graves of eligible veterans buried in national, state, or private cemeteries. Niche covers are available for columbaria. Presidential Memorial Certificates and burial flags are also available. Bronze, granite, and marble options.",
    category: 'burial',
    source: 'official_va',
    eligibilityRules: [
      'Veteran must have received honorable or general discharge',
      'Veteran must have died on or after November 1, 1990 for private cemetery marker',
      'All veterans regardless of date of death for national/state cemetery',
    ],
    applicationSteps: [
      'Apply using VA Form 40-1330 for cemetery or private cemetery',
      'Cemetery or next of kin submits application',
      'VA ships marker directly to cemetery or applicant',
    ],
    cfr: '38 CFR Part 38',
    officialUrl: 'https://www.va.gov/burials-memorials/memorial-items/headstones-markers-medallions/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['headstone', 'marker', 'grave', 'memorial', 'flag'],
  },

  // ─── Family (5) ───────────────────────────────────────────────────────────────

  {
    id: 'fa-001',
    title: 'CHAMPVA Health Insurance',
    summary: 'VA health insurance for dependents of veterans with permanent and total disabilities',
    description: "CHAMPVA (Civilian Health and Medical Program of the Department of Veterans Affairs) provides health care coverage to eligible dependents of veterans who are permanently and totally disabled due to a service-connected condition, or who died from a service-connected condition. Covers most medically necessary services.",
    category: 'family',
    source: 'official_va',
    eligibilityRules: [
      'Veteran is permanently and totally disabled from a service-connected condition, OR',
      'Veteran died from a service-connected condition, OR',
      'Veteran died on active duty',
      'Applicant is the non-Medicare-eligible spouse or dependent child',
    ],
    applicationSteps: [
      'Apply using VA Form 10-10d',
      'Provide sponsor veteran\'s VA rating decision and dependent documentation',
      'VA Health Eligibility Center in Denver processes applications',
    ],
    cfr: '38 CFR Part 17 Subpart C',
    officialUrl: 'https://www.va.gov/health-care/family-caregiver-benefits/champva/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['champva', 'dependent', 'spouse', 'health-insurance', 'family'],
  },

  {
    id: 'fa-002',
    title: 'Family Caregiver Stipend',
    summary: 'Monthly stipend for family members providing care to eligible post-9/11 veterans',
    description: "The Program of Comprehensive Assistance for Family Caregivers provides a monthly stipend to designated primary family caregivers of eligible post-9/11 veterans. The stipend amount is based on the level of care needed and the caregiver's geographic location. Also includes health coverage, mental health services, and respite care.",
    category: 'family',
    source: 'official_va',
    eligibilityRules: [
      'Veteran served on or after September 11, 2001',
      'Veteran needs personal care services for at least 6 continuous months',
      'Caregiver is a family member (spouse, parent, sibling, child, in-law)',
      'Both veteran and caregiver must be approved by VA',
    ],
    applicationSteps: [
      'Submit VA Form 10-10CG jointly (veteran and caregiver)',
      'VA conducts home assessment visit',
      'Caregiver completes required training',
    ],
    cfr: '38 CFR Part 71',
    officialUrl: 'https://www.caregiver.va.gov/PCAFC.asp',
    stateCode: null,
    isHiddenGem: false,
    tags: ['caregiver', 'stipend', 'family', 'post-911', 'monthly-payment'],
  },

  {
    id: 'fa-003',
    title: "Fry Scholarship",
    summary: 'Post-9/11 GI Bill benefits for children and spouses of service members who died in the line of duty',
    description: "The Marine Gunnery Sergeant John David Fry Scholarship provides Post-9/11 GI Bill benefits to the children and surviving spouses of servicemembers who died in the line of duty after September 11, 2001. Children may use it after age 33; spouses must use benefits within 15 years of servicemember's death.",
    category: 'family',
    source: 'official_va',
    eligibilityRules: [
      'Servicemember died in the line of duty on or after September 11, 2001',
      'Applicant is an eligible surviving dependent child or spouse',
      'Children: between ages 18 and 33',
      'Spouses: within 15 years of servicemember\'s death',
    ],
    applicationSteps: [
      'Apply online at VA.gov using VA Form 22-5490',
      'Provide servicemember\'s death documentation',
      'Receive Certificate of Eligibility',
    ],
    cfr: '38 USC 3311(b)(9)',
    officialUrl: 'https://www.va.gov/education/survivor-dependent-benefits/fry-scholarship/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['fry-scholarship', 'gi-bill', 'survivor', 'dependent', 'line-of-duty'],
  },

  {
    id: 'fa-004',
    title: 'Military Spouse Career Advancement Account (MyCAA)',
    summary: 'Up to $4,000 in career training scholarships for spouses of active duty servicemembers',
    description: "MyCAA provides eligible military spouses with up to $4,000 in financial assistance ($2,000 per year) for licensing, certifications, and associate degrees that lead to portable careers. Managed by DoD through the Spouse Education and Career Opportunities program.",
    category: 'family',
    source: 'vso_verified',
    eligibilityRules: [
      'Spouse of active duty servicemember in pay grades E-1 through E-5, W-1 through W-2, or O-1 through O-2',
      'Servicemember has not separated from service',
      'Enrolled in degree, license, or certification program',
    ],
    applicationSteps: [
      'Create account at mycaa.com',
      'Verify servicemember eligibility',
      'Apply for financial assistance before starting classes',
    ],
    cfr: 'DoD Policy',
    officialUrl: 'https://myseco.militaryonesource.mil/portal/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['mycaa', 'spouse', 'scholarship', 'career', 'education'],
  },

  {
    id: 'fa-005',
    title: 'Children of Vietnam Veterans Birth Defects Program',
    summary: 'Health care benefits and monthly compensation for children born with certain birth defects to Vietnam veterans',
    description: "Children of Vietnam veterans who were born with certain birth defects may be eligible for health care and monthly compensation through VA. The program covers conditions associated with Vietnam service, specifically spina bifida and certain other birth defects. Adopted children may also qualify.",
    category: 'family',
    source: 'official_va',
    eligibilityRules: [
      'Child of a Vietnam or Korea DMZ veteran',
      'Born with spina bifida or covered birth defect',
      'Biological child born after veteran\'s service',
    ],
    applicationSteps: [
      'Apply using VA Form 21-0304',
      'Submit veteran\'s service records showing Vietnam service',
      'Provide child\'s medical documentation of birth defect',
    ],
    cfr: '38 CFR Part 3 Subpart F',
    officialUrl: 'https://www.va.gov/disability/eligibility/special-claims/birth-defects/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['birth-defects', 'vietnam', 'children', 'spina-bifida', 'family'],
  },

  // ─── Transition (4) ───────────────────────────────────────────────────────────

  {
    id: 'tr-001',
    title: 'Solid Start Program',
    summary: 'VA calls newly separated veterans three times in first year to connect them to benefits',
    description: "VA Solid Start reaches out to veterans within 90 days of separation, at the 6-month mark, and at the 1-year mark to check in and connect them to VA benefits and services. Helps new veterans navigate the VA system before needs become acute.",
    category: 'transition',
    source: 'official_va',
    eligibilityRules: [
      'Separated from active duty service',
      'VA receives separation information from DoD',
    ],
    applicationSteps: [
      'No action needed — VA will call you',
      'Can opt in at VA.gov if not contacted',
      'Calls come from 1-800-827-1000',
    ],
    cfr: 'VA Administrative',
    officialUrl: 'https://www.va.gov/solid-start/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['solid-start', 'new-veteran', 'outreach', 'transition', 'first-year'],
  },

  {
    id: 'tr-002',
    title: "Veterans' Preference Hiring (State Government)",
    summary: 'State-level hiring preferences and points for veterans in government employment',
    description: 'Most states offer veterans preference in state government hiring, similar to federal preference. Many states also extend preference to spouses of disabled veterans, surviving spouses, and veterans with disabilities. State programs vary in point values and qualifying criteria.',
    category: 'transition',
    source: 'vso_verified',
    eligibilityRules: [
      'Honorable or general discharge',
      'State residency may be required',
      'Specific service requirements vary by state',
    ],
    applicationSteps: [
      'Check your state workforce agency for veterans preference policies',
      'Claim preference on state employment application',
      'Submit DD-214 and disability documentation if applicable',
    ],
    cfr: 'State Law Varies',
    officialUrl: 'https://www.dol.gov/agencies/vets/programs/vets-preference',
    stateCode: null,
    isHiddenGem: false,
    tags: ['state-hiring', 'veterans-preference', 'government', 'employment', 'transition'],
  },

  {
    id: 'tr-003',
    title: 'American Corporate Partners (ACP) Mentorship',
    summary: 'Free year-long mentorship with business professionals for transitioning veterans',
    description: "ACP's mentorship program pairs transitioning servicemembers and veterans with employees from major corporations for one-on-one career mentorship. Mentors help with resume review, networking, career planning, and industry-specific guidance. Completely free to veterans.",
    category: 'transition',
    source: 'vso_verified',
    eligibilityRules: [
      'Veteran or transitioning servicemember within 2 years of separation',
      'Spouses of active duty servicemembers also eligible',
    ],
    applicationSteps: [
      'Apply online at acp-usa.org',
      'Complete profile with career interests and goals',
      'ACP matches with an appropriate corporate mentor',
    ],
    cfr: 'Non-Profit Program',
    officialUrl: 'https://www.acp-usa.org/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['mentorship', 'career', 'corporate', 'networking', 'transition'],
  },

  {
    id: 'tr-004',
    title: 'Hire Heroes USA',
    summary: 'Free career coaching, resume writing, and job placement for veterans and military spouses',
    description: "Hire Heroes USA provides free personalized job coaching and federal resume help to transitioning servicemembers, veterans, and military spouses. Services include career coaching, resume reviews, federal resume writing, mock interviews, and LinkedIn profile optimization.",
    category: 'transition',
    source: 'vso_verified',
    eligibilityRules: [
      'U.S. veteran or transitioning servicemember',
      'Military spouse also eligible',
    ],
    applicationSteps: [
      'Register online at hireheroesusa.org',
      'Complete intake form',
      'Schedule first session with career transition specialist',
    ],
    cfr: 'Non-Profit Program',
    officialUrl: 'https://www.hireheroesusa.org/',
    stateCode: null,
    isHiddenGem: false,
    tags: ['job-coaching', 'resume', 'federal-resume', 'hiring', 'transition'],
  },

  // ─── State-Specific Examples (2) ──────────────────────────────────────────────

  {
    id: 'tx-001',
    title: 'Texas Hazelwood Act',
    summary: 'Up to 150 credit hours of free Texas public university tuition for eligible veterans',
    description: "Texas' Hazelwood Act provides up to 150 credit hours of free tuition at Texas public colleges and universities for eligible Texas veterans. Unlike most education benefits, it covers tuition regardless of other grants or scholarships received. The Legacy Benefit extends unused hours to dependent children.",
    category: 'education',
    source: 'vso_verified',
    eligibilityRules: [
      'Texas resident at time of entry into military service, OR',
      'Texas resident for 12 months before enrollment',
      'Honorable or general discharge',
      'No federal veteran education benefits remaining (or using in conjunction)',
    ],
    applicationSteps: [
      'Contact financial aid office at Texas public university or college',
      'Submit Hazelwood application and DD-214',
      'Approval granted semester by semester',
    ],
    cfr: 'Texas Education Code 54.341',
    officialUrl: 'https://www.tvc.texas.gov/education/hazelwood-act/',
    stateCode: 'TX',
    isHiddenGem: false,
    tags: ['texas', 'hazelwood', 'tuition-free', 'college', 'state-benefit'],
  },

  {
    id: 'ca-001',
    title: 'California College Fee Waiver',
    summary: 'Free tuition at California Community Colleges and CSU for qualifying veterans',
    description: "California's College Fee Waiver Program (CVWF) provides waiver of mandatory system fees at California Community Colleges for qualifying veterans and their dependents. Four plans cover different categories: Plan A for non-service-connected pension recipients, Plan B for service-connected disability 0%+ veterans, Plan C for dependents, Plan D for recipients of Medal of Honor.",
    category: 'education',
    source: 'vso_verified',
    eligibilityRules: [
      'California resident',
      'Service-connected disability (Plan B) or receiving VA pension (Plan A)',
      'Dependent of 100% disabled veteran or veteran who died from service (Plan C)',
    ],
    applicationSteps: [
      'Contact California Department of Veterans Affairs',
      'Submit DD-214 and VA rating documentation',
      'School financial aid office processes the waiver',
    ],
    cfr: 'California Education Code 66025.3',
    officialUrl: 'https://www.calvet.ca.gov/VetServices/Pages/College-Fee-Waiver.aspx',
    stateCode: 'CA',
    isHiddenGem: false,
    tags: ['california', 'fee-waiver', 'community-college', 'state-benefit', 'tuition'],
  },

];
